version: '3.8'
services:
   client:
      build: .
      image: bohemus307/salty_dog1.0.0:latest
      ports:
         - 3030:3030
      environment:
         - NODE_ENV=dev
         - DATABASE_URL=postgresql://postgres:password@postgres:5432/saltydog1     
   db:
      image: postgres:latest
      ports:
         - "5432:5432"
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=saltydog1
      volumes:
         - ./data/postgres:/var/lib/postgresql/data 
                 


