version: '3.8'
services:
   client:
      build: .
      image: bohemus307/salty_dog1.0.0:latest
      ports:
         - 3030:3030
      environment:
         - NODE_ENV=prod
         - DATABASE_URL=postgres://postgres:password@host.docker.internal:5432/saltydog1
         - DEV_DB_HOST=host.docker.internal
         - PGUSER=postgres 
         - PGPASSWORD=password  
         - PGDATABASE=saltydog1
           
   db:
      image: postgres:latest
      ports:
         - "5432:5432"
      volumes:
         - ./data/postgres:/var/lib/postgresql/data 
                 


